# Numpy Basic

## The data type

- The data type can be used as the dimension representation.
- Using like the linear equation
- `numpy` package is used to define the linear equations

​	 **note** many data science techniques use the linear equation to manipulate the value.

There are two type of data

**Scalar**

- a number
- no direction



**Vector**

- list of numbers
- identify that point in space
- use as the direction

If we have the point (3,4)

![image-20230731183241242](./assets/image-20230731183241242.png)

* $\overrightarrow{a}$ show the scalar value of the vector

* aka the absolute value

* The dimension may have more than one di### Creating the vector



using the function array which will convert the list to an array

```
import numpy as np
v = np.array ([1.,2.,3.])
```

now v will act as the vector in linear algebra instead of a list

In [1]:
import numpy as np
v = np.array ([1.,2.,3.])

### Create the numpy as given

```python
import numpy as np
v1 = np.array([1.,3,-5])
v2 = np.array([4,-2,-1])
```

Then try to draw the 3d image for this vector?

In [2]:
import numpy as np
v1 = np.array([1.,3,-5])
v2 = np.array([4,-2,-1])

Try to guess what is the result of this two command

```python
print (2*v1)
print (v1/2)
```



In [3]:
print (2*v1)
print (v1/2)

[  2.   6. -10.]
[ 0.5  1.5 -2.5]


Try this combination

```python
print(3*v1)
print (v1 + v2)
```

In [4]:
print(3*v1)
print (v1 + v2)

[  3.   9. -15.]
[ 5.  1. -6.]


Try this code
```python
v4 = np.array([1,2,3,4,5])
print (v1 + v4)
```

In [5]:
v4 = np.array([1,2,3,4,5])
print (v1 + v4)

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

## Matrix

Matrix is a data structure that consists of rows and columns.

The matrix can be implemented using the numpy

![image-20230731184629040](./assets/image-20230731184629040.png)

<img src="./assets/1024px-Matrix.svg.png" alt="undefined" style="zoom:50%;" />

**Note**

Vectors are no column - and no row matrices

> the $n$ vector, and $n \times 1$ and a $1 \times n$ matrix are three different objects even if they contain the same data.



To create the matrix

using array function, but from the list of the list instead

```python
M = np.array([[1.,2],
              [0.,1]])
M
```

In [6]:
M = np.array([[1.,2],
              [0.,1]])
M

array([[1., 2.],
       [0., 1.]])

#### shape function

To define the number of raw, and column of the matrix

```python
np.shape(M)
```

In [7]:
np.shape(M)

(2, 2)

#### Task

Create this matrix and show the shape of the matrix
$$
\begin{bmatrix}
    1 & 2 & 3 & 4 \\
    5 & 6 & 7 & 8 \\
\end{bmatrix}
$$

In [10]:
import numpy as np
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


#### reshape

change the column and matrix

try

```python
K = M.reshape(4,1)
K
```

In [11]:
K = M.reshape(4,1)
K

array([[1.],
       [2.],
       [0.],
       [1.]])

```python
L = M.reshape(1,4)
```

In [12]:
L = M.reshape(1,4)

The reshape matrix should be the same amount of data; otherwise, the error will be occurred.

Try to change your created data to 3*3 matrix from matrix M


In [15]:
A= M.reshape(3,3)

ValueError: cannot reshape array of size 4 into shape (3,3)

Try to make it to 4 x 2 matrix

In [16]:
B= M.reshape(4,2)

ValueError: cannot reshape array of size 4 into shape (4,2)

Try to make it as 2,2,2 matrix

In [17]:
C= M.reshape(2,2,2)

ValueError: cannot reshape array of size 4 into shape (2,2,2)

## Using other packages

We can create the files which is contains some function by created `my_funcs.py` and post it near by this code (in the same directory)

```python
def print_a():
    print("a")

def print_b():
    print("b")
```

In [18]:
def print_a():
    print("a")

def print_b():
    print("b")

Then type the code as given

```python
import my_funcs
my_funcs.print_a()
my_funcs.print_b()
```

In [19]:
import my_funcs
my_funcs.print_a()
my_funcs.print_b()

ModuleNotFoundError: No module named 'my_funcs'

### import thechniques

* import module directly
```python
import math
print(math.pi)

In [20]:
import math
print(math.pi)

3.141592653589793



* using static import
> import the function or attribute directly, no need to add the package name when call

```python
from math import pi
# Note that in the above examples,
# we used math.pi. Here we have to used pi direcly.
print(pi)
```

In [21]:
from math import pi
# Note that in the above examples,
# we used math.pi. Here we have to used pi direcly.
print(pi)

3.141592653589793


* static import to use all methods in the package
```python
from math import *
print(pi)
print(factorial(6))
```

In [22]:
from math import *
print(pi)
print(factorial(6))

3.141592653589793
720


What do we use here?
  ```python
import numpy as np
from scipy.linalg import solve
A = np.array([[1.,2.],[3.,4.]])
b = np.array([1.,4.])
x = solve(A,b)
print(x)
```

In [23]:
import numpy as np
from scipy.linalg import solve
A = np.array([[1.,2.],[3.,4.]])
b = np.array([1.,4.])
x = solve(A,b)
print(x)

[ 2.  -0.5]


# Linear Programming



Using Linear algebra to help people



## Using the Decision support system

- computer-based information system
- supports business or organizational decision-making
- DSS serve the management, operations, and planning level of and organization
- help to make decision
  - of the situation which may be rapidly chaining and not easily specified in advance

## Optimization



- selection of the best elements
- from a set of available alternatives

![image-20230801172230114](./assets/image-20230801172230114.png)

**The best solution**

if we have many relationships

![image-20230801172343701](./assets/image-20230801172343701.png)

### Steps for Formulating and Optimization Model

1. Obtain Data
2. Define the decision variables
3. Define the objective functions (in term of the decision variables)
4. Write the constraints as equalities or inqualities
------

### Characteristics of Linear Programming

- Continuous- valued variables

- No dependence between variables

  - The contribution of each variable to the objective or constraints is independent of that from the other variables

    > NO $x_1 \cdot x_2$

  - The contribution of each variable to the objective or constraints is directly proportional to the variable value

    > No $x^n or \, x^2  \, x^3$

- The model is deterministic

- Not guarantee to get feasible solution

### Example

In the custom-made shirt factory, shirt A and shirt B are produced.

&emsp;Shirt type A

&emsp;&emsp;requires 9 hrs of labor and 12 buttons

&emsp;&emsp;the profit is 350 THB/unit

&emsp;Shirt type B

&emsp;&emsp;requires 6 hours and labor of 16 buttons

&emsp;&emsp;the profit is 300 THB/unit

There are 2880 buttons, 1566 hrs. of labor, and 200 cloths available in the factory

How many type A and type B shirts that the manufacturer should produce?

Try to write the related equations?


#### Step 1

![image-20230801165028646](./assets/image-20230801165028646.png)

#### Step 2

![image-20230801165047841](./assets/image-20230801165047841.png)

#### Step 3

![image-20230801165103187](./assets/image-20230801165103187.png)

#### Step 4

![image-20230801165117222](./assets/image-20230801165117222.png)



#### Step 5

![image-20230801165132452](./assets/image-20230801165132452.png)

#### Step 6

![image-20230801165148808](./assets/image-20230801165148808.png)

#### Step 7

![image-20230801165204453](./assets/image-20230801165204453.png)

#### Step 8

![image-20230801165219675](./assets/image-20230801165219675.png)



## Using Python Linear Programming



Using the pulp component

the given work can be implement with this code

```python
from pulp import *
# create the new problem
prob = LpProblem("Cloth_Problem",LpMaximize)
# add the variable https://www.coin-or.org/PuLP/pulp.html
x1 = LpVariable("Shirt A",lowBound = 0,cat='Integer')
x2 = LpVariable("Shirt B",lowBound = 0,cat='Integer')
# add the constraint
c1 = x1 + x2 <= 200
c2 = 9*x1+6*x2 <= 1566
c3 = 12*x1 + 16*x2 <= 2880
# Objective value
obj = 350*x1 + 300*x2

prob += obj, "Maximum profit"
prob += c1, "The amount of all shirt"
prob += c2, "The labour amount"
prob += c3, "The button amount"

prob.solve()

print("Status:" + LpStatus[prob.status])
for v in prob.variables():
    print (v.name, "=", v.varValue)
for v in prob.constraints:
    print (v)
print ("Total profit is" , value(prob.objective))
print ("Total profit is" , value(prob.objective))
```

**Note** you may not need to type the comments

**Note** you may need to run the command `pip install pulp` to install the pacakge to the run time first.

this is just one implementation of the solution

In [24]:
!pip install pulp

In [25]:
from pulp import *
# create the new problem
prob = LpProblem("Cloth_Problem",LpMaximize)
# add the variable https://www.coin-or.org/PuLP/pulp.html
x1 = LpVariable("Shirt A",lowBound = 0,cat='Integer')
x2 = LpVariable("Shirt B",lowBound = 0,cat='Integer')
# add the constraint
c1 = x1 + x2 <= 200
c2 = 9*x1+6*x2 <= 1566
c3 = 12*x1 + 16*x2 <= 2880
# Objective value
obj = 350*x1 + 300*x2

prob += obj, "Maximum profit"
prob += c1, "The amount of all shirt"
prob += c2, "The labour amount"
prob += c3, "The button amount"

prob.solve()

print("Status:" + LpStatus[prob.status])
for v in prob.variables():
    print (v.name, "=", v.varValue)
for v in prob.constraints:
    print (v)
print ("Total profit is" , value(prob.objective))
print ("Total profit is" , value(prob.objective))

Status:Optimal
Shirt_A = 122.0
Shirt_B = 78.0
The_amount_of_all_shirt
The_labour_amount
The_button_amount
Total profit is 66100.0
Total profit is 66100.0


### Task

**The Ice-cream shop**

Assume you open your ice cream shop, there are only two types of ice cream, vanilla and strawberry. When a box of ice cream is sold, you will get the benefit for $2 for vanilla ice cream and $3 for strawberry ice cream. To make the ice cream, the fresh milk is required. To make a box of vanilla ice cream requires 0.5 liter and strawberry ice cream requires 0.2 liter. You daily order 10 liters of fresh milk. To promote your ice cream shop, you give a doll for each ice cream box. The number of dolls, that you can give to customers, is 30 dolls per day.

So, how many boxes of vanilla ice cream and strawberry ice cream that you would like to produce to get maximum profit ?



In [26]:
from pulp import *

# Create the problem
prob = LpProblem("Ice_Cream_Problem", LpMaximize)

# Define variables
x1 = LpVariable("Vanilla_Ice_Cream", lowBound=0, cat='Integer')  # Number of boxes of vanilla ice cream
x2 = LpVariable("Strawberry_Ice_Cream", lowBound=0, cat='Integer')  # Number of boxes of strawberry ice cream

# Define constraints
c1 = 0.5*x1 + 0.2*x2 <= 10  # Fresh milk constraint (in liters)
c2 = x1 + x2 <= 30  # Dolls constraint

# Define objective function (profit)
profit = 2*x1 + 3*x2

# Add objective function and constraints to the problem
prob += profit, "Maximum Profit"
prob += c1, "Fresh Milk Constraint"
prob += c2, "Dolls Constraint"

# Solve the problem
prob.solve()

# Print the results
print("Status:", LpStatus[prob.status])
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Total profit is", value(prob.objective))


Status: Optimal
Strawberry_Ice_Cream = 30.0
Vanilla_Ice_Cream = 0.0
Total profit is 90.0


### Portfolio Selection

Maximize the return rate

with the given portfolio

![image-20230801165530908](./assets/image-20230801165530908.png)

With these policies

- Total amount= €90000
- Amount in shares of a sector no larger than50% of total available
- Amount in shares with the larger return of a sector less or equal to 80% of sector’s total amount
- Amount in manufacturing company Β less or equal to 10% of the whole share amount
- Amount in mutual funds less or equal to 25% of the amount in manufacturing shares

In [27]:
from pulp import *

# Create the problem
prob = LpProblem("Investment_Portfolio", LpMaximize)

# Total amount available for investment
total_amount = 90000

# Define variables for the amount invested in each share and fund
A = LpVariable("Share_A", lowBound=0)
B = LpVariable("Share_B", lowBound=0)
C = LpVariable("Share_C", lowBound=0)
D = LpVariable("Share_D", lowBound=0)
E = LpVariable("Fund_E", lowBound=0)
Z = LpVariable("Fund_Z", lowBound=0)

# Define expected annual return of investments
returns = {"Share_A": 0.154, "Share_B": 0.192, "Share_C": 0.187, "Share_D": 0.135, "Fund_E": 0.178, "Fund_Z": 0.163}

# Add constraints
prob += A + B + C + D + E + Z == total_amount  # Total amount constraint
prob += A + B + C + D <= 0.5 * total_amount  # Shares of a sector constraint
prob += B <= 0.8 * (A + B + C + D)  # Larger return of a sector constraint
prob += B <= 0.1 * (A + B + C + D)  # Manufacturing company B constraint
prob += E + Z <= 0.25 * (A + B + C + D)  # Mutual funds constraint

# Define objective function (maximize the return rate)
profit = returns["Share_A"]*A + returns["Share_B"]*B + returns["Share_C"]*C + returns["Share_D"]*D + returns["Fund_E"]*E + returns["Fund_Z"]*Z
prob += profit, "Maximize Return Rate"

# Solve the problem
prob.solve()

# Print the results
print("Status:", LpStatus[prob.status])
for v in prob.variables():
    print(v.name, "=", v.varValue)
print("Total return rate is", value(prob.objective))


Status: Infeasible
Fund_E = 45000.0
Fund_Z = 0.0
Share_A = 0.0
Share_B = 4500.0
Share_C = 40500.0
Share_D = 0.0
Total return rate is 16447.5
